#!/bin/bash
read -p "enter the file name: " name
touch $name
#read -p "enter the code: " code
if [ $name == README.md ]; then
read -p "enter the code: " code
echo -e $code >> $name
else
#echo -e '#!/bin/bash\n' >> $name
read -p "enter your option[cp|lin|vim]: " option
if [ $option == vim ]; then
echo -e '#!/bin/bash\n' >> $name
vim $name
elif [ $option == lin ]; then
count=0
code="- "
        #echo -e '#!/bin/bash\n' >> $name
while [ ${#code} -gt 0 ]; do
echo -e $code >> $name
read -p "enter the code line ${count[0]} ${count[1]}:" code
let count=count+1
done
        #echo -e '#!/bin/bash\n'$code >> $name
elif [ $option == cp ]; then
read -p "enter cp code: " code
echo -e $code >> $name
fi
fi
chmod u+x $name
cat $name
git add .
echo 'enter your commit: '
read -a txt
git commit -m"${txt[0]} ${txt[1]} ${txt[2]} ${txt[3]} ${txt[4]}"
git push
