#!/bin/bash
#!usr/bin/env bash
echo 'put the name of file: '
read name
touch $name
echo -e '#!/bin/bash\n' > $name
echo 'put the code: '
read code
echo $code > $name
git add .
echo 'put the msg: '
read txt
git commit -m txt
git push
